# Generated by Django 4.1.1 on 2022-09-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twikkerprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twikkerprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
