# Generated by Django 4.1.2 on 2022-11-01 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twikkerprofile', '0002_twikkerprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twikkerprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='uploads/default.png', null=True, upload_to='uploads/'),
        ),
    ]
