# Generated by Django 4.1.2 on 2022-11-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twikkerprofile', '0003_alter_twikkerprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='twikkerprofile',
            name='dark_mode',
            field=models.BooleanField(default=True),
        ),
    ]
