# Generated by Django 4.1.3 on 2023-02-16 02:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twikkerprofile', '0004_twikkerprofile_dark_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twikkerprofile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/deues3qyn/image/upload/v1676499936/avatar.png', max_length=255, verbose_name='image'),
        ),
    ]
