# Generated by Django 4.1.3 on 2023-02-16 03:20

import apps.twikkerprofile.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twikkerprofile', '0005_alter_twikkerprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twikkerprofile',
            name='avatar',
            field=apps.twikkerprofile.fields.MockCloudinaryField(default='https://res.cloudinary.com/deues3qyn/image/upload/v1676499936/avatar.png', verbose_name='image'),
        ),
    ]
