services:
#  db:
#    image: postgres
#    volumes:
#      - ./data/db:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_DB=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:7000 && python manage.py migrate && python manage.py migrate feed 0012 --fake && python manage.py migrate && python manage.py migrate twikkerprofile 0006 --fake  && python manage.py migrate
    volumes:
      - .:/code
    ports:
      - "7000:7000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
#    depends_on:
#      - db
