# Generated by Django 4.1.2 on 2022-10-28 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'Message'), ('follower', 'Follower'), ('like', 'Like'), ('dislike', 'Dislike'), ('mention', 'Mention')], max_length=20),
        ),
    ]
