# Generated by Django 4.1.3 on 2023-02-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_by_username',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
