TWEEK_FILTER_RECENTLY = '0'
TWEEK_FILTER_LIKES = '1'
TWEEK_FILTER_SHARES = '2'
TWEEK_FILTER_TYPE = (
    (TWEEK_FILTER_RECENTLY, ('Recently')),
    (TWEEK_FILTER_LIKES, ('Likes')),
    (TWEEK_FILTER_SHARES, ('Shares')),
)
