TWEEK_FILTER_RECENTLY = '0'
TWEEK_FILTER_LIKES = '1'
TWEEK_FILTER_SHARES = '2'
TWEEK_FILTER_TYPE = (
    (TWEEK_FILTER_RECENTLY, ('Recently')),
    (TWEEK_FILTER_LIKES, ('Likes')),
    (TWEEK_FILTER_SHARES, ('Shares')),
)

USER_FILTER_ALPHABETICAL = '0'
USER_FILTER_FOLLOWERS = '1'
USER_FILTER_FOLLOWING = '2'
USER_FILTER_TYPE = (
    (USER_FILTER_ALPHABETICAL, ('Alphabetical')),
    (USER_FILTER_FOLLOWERS, ('Followers')),
    (USER_FILTER_FOLLOWING, ('Following')),
)
