# Generated by Django 4.1.2 on 2022-11-01 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_dislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweek',
            name='retweek',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.tweek'),
        ),
    ]
