# Generated by Django 4.1.2 on 2022-11-02 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_tweek_retweek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweek',
            name='retweek',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.tweek'),
        ),
    ]
