# Generated by Django 4.1.2 on 2022-11-06 19:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0008_alter_tweek_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dislike',
            unique_together={('created_by', 'tweek')},
        ),
    ]
