# Generated by Django 4.1.2 on 2022-11-07 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_alter_dislike_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweek',
            name='comment_from',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='feed.tweek'),
        ),
    ]
