# Generated by Django 4.1.3 on 2023-02-16 03:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_tweek_comment_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweek',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image'),
        ),
    ]
