# Generated by Django 4.1.3 on 2023-02-16 03:22

import apps.twikkerprofile.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_tweek_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweek',
            name='image',
            field=apps.twikkerprofile.fields.MockCloudinaryField(blank=True, default=None, null=True, verbose_name='image'),
        ),
    ]
